#!/bin/bash


sudo ifconfig enp0s31f6 down
sudo ifconfig enp0s31f6 192.168.123.162/24
sudo ifconfig enp0s31f6 up

# sudo route add default gw 192.168.123.161
# sudo route del default gw 192.168.123.161